### ISSUE TITLE
Completion menu shows after pressing <Tab>

### ISSUE THREAD

**Issue by squattingmonk** [thadeudepaula/ide.nvim#1]
When I edit nim files (either with your config or mine), the completion menu pops up after pressing `<Tab>`, regardless of whether there's actually anything to complete. This means I can't press tab multiple times because it starts cycling through completion options. This doesn't happen with other filetypes. My solution was to use `<C-j>` and `<C-k>` for cycling through the completion menu. Do you run into this issue, too?

**Comment by thadeudepaula** [comment]
Yes... but if yout didn't said about I wouldn't perceive it as an issue. There is a way to popup suggestions after n characters. I will look into this see if can enable only after 2 characteres or avoiding after spaces.

**Comment by squattingmonk** [comment]
Yeah, I've tried setting the keyword_length and it doesn't seem to make a difference. Very odd that this is only with nim files.

**Comment by thadeudepaula** [comment]
> Yeah, I've tried setting the keyword_length and it doesn't seem to make a difference. Very odd that this is only with nim files.

A have a hard time with autocompletion... As I never used VSCode, I don't know how it behaves. I hate things popping around and making choices to me, even because it distracts too much. I'm learning to leave with autocompletions, but not too auto.

In my earlier personal configuration I used to have `S-Up` / `S-Down` (`Shift+↑` / `Shift+↓`) to select things. Autocompletion annoyes me every time I want to navigate through the files using arrows.

Really, I'm inclined to set it as default on config, since it is less invasive, so you will really need to choose the completion.

**Comment by thadeudepaula** [comment]
@squattingmonk I pushed the commit thadeudepaula@6d100782 with more previsible keybindings related to the completion menu and also updated readme with them.
